const actionTypes = {
    CART_COUNT: 'CART_COUNT',
    IS_VISIBLE_DETAIL: 'IS_VISIBLE_DETAIL',
    PRODUCT_VISIBLE_IN_DETAIL: 'PRODUCT_VISIBLE_IN_DETAIL',
    IS_CHECK_OUT_SIDE_MENU_OPEN: 'IS_CHECK_OUT_SIDE_MENU_OPEN',
    CART_PRODUCTS: 'CART_PRODUCTS',
    TOTAL_PRICE: 'TOTAL_PRICE',
    ORDER: 'ORDER',
    ORDERS: 'ORDERS',

}

export default actionTypes
